### ISSUE TITLE
Convenience functions

### ISSUE THREAD

**Issue by Boscop** [dnsl48/base91#1]
Thanks for this crate :)
I think it would make sense to add convenience functions:
```rust
fn str_encode(value: &[u8]) -> String; // calls `unsafe { String::from_utf8_unchecked(encode_slice(value)) }`
fn str_decode(value: &str) -> Vec<u8>;
```

Like this: https://docs.rs/base-x/0.2.8/src/base_x/alphabet.rs.html#38

**Comment by dnsl48** [comment]
Hi @Boscop, sure, sounds good!
Would you like to make a PR?
